---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
{{- if .Values.ocp4_workload_openshift_virtualization_workload_tolerations }}
  workloads:
    nodePlacement:
      tolerations:
        {{ .Values.ocp4_workload_openshift_virtualization_workload_tolerations }}
{{- end }}
  enableCommonBootImageImport: {{ ternary "true" "false" (not .Values.external_ceph) }}
