apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kubevirt-hyperconverged.openshift-cnv: ''
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- if .Values.kubevirt.startingCSV }}
  startingCSV: {{ .Values.kubevirt.startingCSV }}
{{- end }}
{{- if .Values.kubevirt.config }}
{{ .Values.kubevirt.config | indent 2 }}
  config:
    env:
    - name: KVM_EMULATION
      value: "true"
{{- end }}
